-- Migration: Workflow Conselho RY
-- Description: Adds tables for Admin/Client/Seller workflow and AI analysis.
-- Generated by: database-architect

-- 1. Create table for extended role configuration
CREATE TABLE IF NOT EXISTS public.users_role_config (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role TEXT CHECK (role IN ('admin', 'client', 'seller', 'strategist')),
    fixed_password_hash TEXT, -- Specific for this workflow's simplified login
    parent_client_id UUID, -- For Sellers belonging to a Client
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Consultancy Templates (Admin Config)
CREATE TABLE IF NOT EXISTS public.consultancy_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT,
    structure_json JSONB NOT NULL DEFAULT '[]'::jsonb, -- Form fields definition
    ai_prompt_config JSONB, -- Instructions for the Head Agent
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    created_by UUID REFERENCES auth.users(id)
);

-- 3. Daily Reports (Seller Input)
-- Note: Re-creating if not exists, adjusting columns
CREATE TABLE IF NOT EXISTS public.daily_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    seller_id UUID REFERENCES auth.users(id) NOT NULL,
    client_id UUID, -- Logical reference to client
    report_date DATE DEFAULT CURRENT_DATE,
    content_json JSONB NOT NULL DEFAULT '{}'::jsonb, -- Answers to template
    audio_transcription TEXT,
    audio_url TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'analyzed', 'error')),
    template_id UUID REFERENCES public.consultancy_templates(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_daily_reports_seller ON public.daily_reports(seller_id);
CREATE INDEX IF NOT EXISTS idx_daily_reports_date ON public.daily_reports(report_date);

-- 4. Strategic Analysis (AI Output)
CREATE TABLE IF NOT EXISTS public.strategic_analysis (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    report_id UUID REFERENCES public.daily_reports(id) ON DELETE CASCADE,
    operational_feedback TEXT,
    tactical_feedback TEXT,
    suggested_scripts JSONB DEFAULT '[]'::jsonb,
    improvement_checklist JSONB DEFAULT '[]'::jsonb,
    processed_model TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. Enable RLS
ALTER TABLE public.users_role_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consultancy_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.strategic_analysis ENABLE ROW LEVEL SECURITY;

-- 6. Policies

-- Role Config: Users read own
DROP POLICY IF EXISTS "Users can read own role config" ON public.users_role_config;
CREATE POLICY "Users can read own role config" ON public.users_role_config
    FOR SELECT USING (auth.uid() = user_id);

-- Templates: Authenticated users can read
DROP POLICY IF EXISTS "Auth users can read templates" ON public.consultancy_templates;
CREATE POLICY "Auth users can read templates" ON public.consultancy_templates
    FOR SELECT TO authenticated USING (true);

-- Reports: Sellers insert, Users view own
DROP POLICY IF EXISTS "Sellers can insert reports" ON public.daily_reports;
CREATE POLICY "Sellers can insert reports" ON public.daily_reports
    FOR INSERT TO authenticated WITH CHECK (auth.uid() = seller_id);

DROP POLICY IF EXISTS "Users view own reports" ON public.daily_reports;
CREATE POLICY "Users view own reports" ON public.daily_reports
    FOR SELECT TO authenticated USING (auth.uid() = seller_id);

-- Analysis: View own report's analysis
DROP POLICY IF EXISTS "Users view analysis of own reports" ON public.strategic_analysis;
CREATE POLICY "Users view analysis of own reports" ON public.strategic_analysis
    FOR SELECT TO authenticated USING (
        EXISTS (
            SELECT 1 FROM public.daily_reports
            WHERE daily_reports.id = strategic_analysis.report_id
            AND daily_reports.seller_id = auth.uid()
        )
    );
